springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
spring.profiles.active=dev
spring.application.name=backend
gemini.api.key=AIzaSyDkYQTmtj1s341HZVBRkiaIPoyz4FPpZjc
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-lite:generateContent
spring.cache.type=simple
spring.data.redis.host=localhost
spring.data.redis.port=6379