spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}

# Database Configuration
spring.datasource.url=${DATASOURCE_URL:jdbc:postgresql://${POSTGRES_HOST:postgres-primary}:${POSTGRES_PORT:5432}/${POSTGRES_DB:ecommerce}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=CET}
spring.datasource.username=${DATASOURCE_USERNAME:${POSTGRES_USER:admin}}
spring.datasource.password=${DATASOURCE_PASSWORD:${POSTGRES_PASSWORD:admin}}
spring.datasource.driver-class-name=${DATASOURCE_DRIVER:org.postgresql.Driver}

# JPA Configuration
spring.jpa.properties.hibernate.dialect=${HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
spring.jpa.hibernate.show-sql=${HIBERNATE_SHOW_SQL:true}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.globally_quoted_identifiers=${HIBERNATE_QUOTED_IDENTIFIERS:true}
spring.jpa.properties.hibernate.format_sql=${HIBERNATE_FORMAT_SQL:true}
spring.cloud.compatibility-verifier.enabled=${CLOUD_COMPATIBILITY_VERIFIER:false}
