springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
spring.application.name=${SPRING_APPLICATION_NAME:backend}

# Gemini API Configuration
gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=${GEMINI_API_URL:https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-lite:generateContent}

# Cache Configuration
spring.cache.type=${SPRING_CACHE_TYPE:redis}

# Database Configuration
spring.datasource.url=${DATASOURCE_URL:jdbc:postgresql://${POSTGRES_HOST:db}:${POSTGRES_PORT:5432}/${POSTGRES_DB:ecommerce}}
spring.datasource.username=${DATASOURCE_USERNAME:${POSTGRES_USER:admin}}
spring.datasource.password=${DATASOURCE_PASSWORD:${POSTGRES_PASSWORD:admin}}
#spring.datasource.driver-class-name=${DATASOURCE_DRIVER:org.postgresql.Driver}

# JPA Configuration
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.properties.hibernate.dialect=${HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
spring.jpa.hibernate.show-sql=${HIBERNATE_SHOW_SQL:true}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.globally_quoted_identifiers=${HIBERNATE_QUOTED_IDENTIFIERS:true}
spring.jpa.properties.hibernate.format_sql=${HIBERNATE_FORMAT_SQL:true}
spring.cloud.compatibility-verifier.enabled=${CLOUD_COMPATIBILITY_VERIFIER:false}

# Redis Configuration
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:864000000}
jwt.header=${JWT_HEADER:Authorization}
jwt.prefix=${JWT_PREFIX:Bearer }
